### ISSUE TITLE
TUIO Receiver Unity 

### ISSUE THREAD

**Issue by justinLifelike** [gregharding/TUIOSimulator#1]
Hi Greg, 

Can or better said how can I use this to make TUIO Receiver so I can receive data from al objects on the table in Unity? 
Thanks in advance! Your help would be much appreciated

**Comment by gregharding** [comment]
hi Justin, TUIOSimulator can be both a client and a server so if you start two instances (same device with different ports, or different devices) you can connect one to the other. Hopefully this helps you see how to send and receive TUIO data.

I haven't been maintaining the project with the latest Unity so there might be some issues with 2019/2020/2021 that I'm not aware of - hopefully everything still works for you. The binary releases should still run fine as a demo of it working.
