### ISSUE TITLE
TUIO for Displax 

### ISSUE THREAD

**Issue by justinLifelike** [gregharding/TUIOSimulator#2]
Thank you for the response to my last issue and for making this awesome simulator! 

I am making an application for a Displax screen (interactive touch screen). 
I was able in making a connection between the simulator and the screen itself, but now I'm trying to attach a certain touch to showing a square on that spot. So with the Displax screen you get these physical circled objects which you can use for object recognition by placing them on the screen. 

What we want to achieve is spawning one of the virtual numbered squares that you see in the simulator on the same spot where you place that physical circled object. 

I can't seem to find how to or where in the code I could inject this. 
Thanks in advance Greg!

**Comment by gregharding** [comment]
hey again Justin, when we used TUIO for our interactive touch tables the ids to identify various objects came from the touch screen surface hardware itself. We used [MultiTaction](https://www.multitaction.com) display hardware that we configured to recognise markers printed on the physical items used on the table.

The TUIO objects sent over the network embed an integer id which the simulator should recognise if they're between 0-7 or 1-8 (can't quite remember the exact range) and show squares for. I assume that these are the type of objects you need to recognise so perhaps double check that the ids your table is sending are in the range 0-7 (or 1-8!). Do you need to recognise a larger range of objects? If so, you should be able to easily extend the range in the simulator by duplicating the existing squares and changing their ids. If you need to recognise arbitrary object ids coming in then the simulator will have to be modified to spawn prefabs for each unique touch/marker for the object ids you want to support (and show the right number in the square etc). For our test rigs I never had to test more than a couple of objects so I didn't need to extend it further and support any object ids that appeared. It's probably more to do with getting Unity to spawn and configure stuff than it is a TUIO problem, so if you're comfortable using Unity you _should_ be ok.

I haven't looked at the simulator for a while (so it's probably quite out of date with the latest Unity) but feel free to ask some questions and I'll do my best to answer them :)

**Comment by justinLifelike** [comment]
Great thanks a lot, Greg! 

I'll go digging again but this really helps it will probably be something within the range then as you suggest because the IDs are high digits. I will check out MultiTaction too. 

I will let you know if I succeed!

Thanks again Greg, you're awesome!

**Comment by gregharding** [comment]
No worries. Maybe check out [TUIOListener](https://github.com/gregharding/TUIOListener) for a command line TUIO debugger/helper. It might help you quickly debug/confirm what object numbers are in use from your table objects.

**Comment by justinLifelike** [comment]
Hi Greg, 

So I checked with TUIOListener and I looked into the code but did not manage to make a change. So the TUIO simulator still perceives the disc as 3 individual cursors/touches. The discs that I use have an ID that range from 401 to 408. 

![Screenshot 2022-08-24 160756](https://user-images.githubusercontent.com/89152236/186445574-a885f454-0d1c-46d4-aae4-35148d411575.jpg)

![Screenshot 2022-08-24 161317](https://user-images.githubusercontent.com/89152236/186445774-bd12c8b2-89ca-450d-a790-dcc6d9b9c4cc.jpg)


This is what I tried: 
- Altering the spawnObjectCount in Surface.cs from 8 to 410; 
- Altering the Range in SurfaceObject.cs from (0,7) to (0,410) 
- In scene Inspector adding 410 sprites and 410 colors while in game mode 
- In scene Inspector setting a specific object to a specific ID (401) 
- Connecting to Displax Connect which is able to identify the disc and its ID

![Screenshot 2022-08-24 162203](https://user-images.githubusercontent.com/89152236/186445806-e00e25c3-22f1-480d-8fd2-057235334183.jpg)

![Screenshot 2022-08-24 162429](https://user-images.githubusercontent.com/89152236/186445818-f9142df1-bf07-4fc5-9753-189e5af79cb3.jpg)


I think I am missing something or did something wrong, could you help me point out what? 

Thanks in advance Greg!!

**Comment by justinLifelike** [comment]
Here is a picture of my Unity scene and where you can see in the bottom left corner that it recognizes 3 touches but no object.
 
![Screenshot 2022-08-24 164637](https://user-images.githubusercontent.com/89152236/186449518-2526b254-4c73-48fb-bef6-28d7cc34ddd0.jpg)

**Comment by justinLifelike** [comment]
Found the solution: 

In de displaxApplication, you have to make a normal Tag and not a Tag+ which I made.

**Comment by gregharding** [comment]
hey Justin, nice one tracking it down. I would not have been able much with the displaxApplication configuration!
